# Docker Compose file containing redis
version: '3'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  enstate:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
